### ISSUE TITLE
The problem of installation

### ISSUE THREAD

**Issue by lisch7** [zhanghao-njmu/SCP#136] opened 2023-07-13 17:17 UTC
I have installed the SCP packages in R and created the SCP python environment following the instructions on Github. But in Rstuio, some packages were not installed successfully. So I installed them manually. But it doesn't work. How can I solve this problem? Thanks.

![image](https://github.com/zhanghao-njmu/SCP/assets/103273640/5581a30a-d63f-47fc-9e15-f6c3fb3046d1)

 pip list in SCP_env
Package             Version
-------------------  ---------`
anndata             0.9.1
annoy               1.17.3
backports.zoneinfo  0.2.1
blosc2              2.0.0
click               8.1.5
cmake               3.26.4
contourpy           1.1.0
cycler              0.11.0
Cython              0.29.36
fcsparser           0.2.4
fonttools           4.41.0
future              0.18.3
h5py                3.9.0
igraph              0.10.2
imageio             2.31.1
importlib-metadata  6.8.0
importlib-resources 6.0.0
jax                 0.4.13
jaxlib              0.4.13
jaxopt              0.7
joblib              1.3.1
kiwisolver          1.4.4
lazy_loader         0.3
leidenalg           0.10.0
llvmlite            0.38.1
loompy              3.0.7
matplotlib          3.6.3
mellon              1.3.1
ml-dtypes           0.2.0
msgpack             1.0.5
natsort             8.4.0
ndindex             1.7
networkx            3.1
numba               0.55.2
numexpr             2.8.4
numpy               1.21.6
numpy-groupies      0.9.22
opt-einsum          3.3.0
packaging           23.1
palantir            1.3.0
pandas              1.3.5
patsy               0.5.3
Pillow              10.0.0
pip                 23.1.2
progressbar2        4.2.0
py-cpuinfo          9.0.0
pygam               0.8.0
pynndescent         0.5.10
pyparsing           3.1.0
python-dateutil     2.8.2
python-igraph       0.10.2
python-utils        3.7.0
pytz                2023.3
PyWavelets          1.4.1
scanpy              1.9.3
scikit-image        0.21.0
scikit-learn        1.1.2
scipy               1.10.1
scrublet            0.2.3
scvelo              0.2.5
seaborn             0.12.2
session-info        1.0.0
setuptools          68.0.0
six                 1.16.0
statsmodels         0.14.0
stdlib-list         0.9.0
tables              3.8.0
texttable           1.6.7
threadpoolctl       3.2.0
tifffile            2023.7.10
tqdm                4.65.0
typing_extensions   4.7.1
tzdata              2023.3
tzlocal             5.0.1
umap-learn          0.5.3
versioned-hdf5      1.3.13
wheel               0.38.4
zipp                3.16.1

**Comment by BenjaminDEMAILLE** [comment] 2023-07-19 10:21
Same for me on M1 Max

**Comment by 1637936665** [comment] 2023-08-04 05:18
pip install palantir==1.2就可以安装了，但是有些包会升级，例如numpy会升级到1.24

**Comment by 1637936665** [comment] 2023-08-04 05:26
Python 3.8.17
pip 23.2.1

pip install setuptools==68.0.0 wheel==0.41.0  numpy==1.21.6 numba==0.55.2 scikit-learn==1.1.2 pandas==1.3.5 python-igraph==0.10.2 matplotlib==3.6.3 scipy==1.10.1 versioned-hdf5==1.3.14 leidenalg==0.10.1 scanpy==1.9.3 scvelo==0.2.5 palantir==1.2

**Comment by zhanghao-njmu** [comment] 2023-08-28 09:57
The package conflict issues caused by the Palantir Python package have been resolved in SCP v0.5.1, with Palantir being forced to version 1.0.1

**Closed** 2023-09-14 09:42 UTC
